// <auto-generated />
namespace LTQLDbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Persion_talble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Persion_talble));
        
        string IMigrationMetadata.Id
        {
            get { return "202110260016339_Persion_talble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
